In [1]:
import numpy as np

In [2]:
data1 = [1, 2, 3, 4, 5]
data1

[1, 2, 3, 4, 5]

In [3]:
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4, 5])

In [4]:
arr2 = np.array([1, 2, 3, 4, 5])
arr2

array([1, 2, 3, 4, 5])

In [5]:
arr1.shape #array의 차원, 크기

(5,)

In [6]:
arr1.dtype

dtype('int32')

In [7]:
arr2 = np.array([[ 1, 2, 3], 
                 [ 4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr2.shape #array의 차원, 크기

(2, 3)

In [9]:
arr2.dtype

dtype('int32')

In [10]:
arr3 = np.array(['Seoul', 'Busan'])
arr3.dtype

dtype('<U5')

In [11]:
np.zeros((3, 5)) #크기를 인자로 받고 모든 요소가 0인 array 만듬. 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones((3, 5)) #크기를 인자로 받고 모든 요소가 1인 array 만듬.

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.arange(10) #인자로 받는 값 만큼 1씩 증가하는 1차원 array 만듬.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(3, 10) #하나의 인자 : 0~인자 

array([3, 4, 5, 6, 7, 8, 9])

In [15]:
arr1 = np.array([[1, 2, 3], 
                 [4, 5, 6]])
arr2 = np.array([[4, 5, 6], 
                 [1, 2, 3]])
print(arr1.shape)
print(arr2.shape)

(2, 3)
(2, 3)


In [16]:
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[[5 7 9]
 [5 7 9]]
[[-3 -3 -3]
 [ 3  3  3]]
[[ 4 10 18]
 [ 4 10 18]]
[[0.25 0.4  0.5 ]
 [4.   2.5  2.  ]]


In [17]:
arr1 * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [18]:
arr1 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [5]:
arr1 = np.array([[1, 2, 3, 4]
                ,[5, 6, 7, 8]
                ,[9, 10, 11, 12]])
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
print(arr1[0, 1])
print(arr1[0][1])

2
2


In [7]:
print(arr1[0, :])
print(arr1[1, :])
print(arr1[2, :])
print(arr1[:, 0])

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[1 5 9]


In [8]:
last = np.array(['김', '이', '박'])
first = np.array([['김민준', '김서준', '김예준']
                 ,['이도윤', '이시우', '이주원']
                 ,['박하준', '박지호', '박지후']])
last == '김'

array([ True, False, False])

In [9]:
name_김 = (last == '김')
name_이 = (last == '이')
name_박 = (last == '박')
print(name_김)
print(name_이)
print(name_박)
print(first[name_김, :])
print(first[name_이, :])
print(first[name_박, :])

[ True False False]
[False  True False]
[False False  True]
[['김민준' '김서준' '김예준']]
[['이도윤' '이시우' '이주원']]
[['박하준' '박지호' '박지후']]


In [24]:
array_data = np.array([1, 2, 3, 4])
array_mask = array_data > 2
filtered_data = array_data[array_mask]
print(filtered_data)

[3 4]


In [11]:
arr1 = np.array([[1, 2, -3]
                ,[4, 5, -6]
                ,[7, 8, -9]])

In [12]:
print(np.abs(arr1))
print(np.sqrt(arr1)) #음수는 계산X
print(np.square(arr1)) 
print(np.log(arr1)) #음수는 계산X
print(np.sign(arr1))
print(np.sin(arr1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1.         1.41421356        nan]
 [2.         2.23606798        nan]
 [2.64575131 2.82842712        nan]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[0.         0.69314718        nan]
 [1.38629436 1.60943791        nan]
 [1.94591015 2.07944154        nan]]
[[ 1  1 -1]
 [ 1  1 -1]
 [ 1  1 -1]]
[[ 0.84147098  0.90929743 -0.14112001]
 [-0.7568025  -0.95892427  0.2794155 ]
 [ 0.6569866   0.98935825 -0.41211849]]


<ipython-input-12-897da1719e40>:2: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(arr1)) #음수는 계산X
<ipython-input-12-897da1719e40>:4: RuntimeWarning: invalid value encountered in log
  print(np.log(arr1)) #음수는 계산X


In [18]:
arr1 = np.random.rand(3, 2) #0 ~ 1 의 표준정규분포 난수
arr2 = np.random.randint(5) #1부터 n-1까지 랜덤숫자 1개
arr3 = np.random.randn(3, 2) #평균0, 표준편차1의 표준정규분포 난수
print(arr1)
print(arr2)
print(arr3)

[[0.29785637 0.20063008]
 [0.86735777 0.64623941]
 [0.29989464 0.21811074]]
4
[[ 1.15854772 -0.01571111]
 [-0.36144805 -0.44091674]
 [-1.06838515  0.41455215]]


In [19]:
arr4 = np.random.randn(3, 2)
arr4

array([[ 0.55091616, -1.23061056],
       [ 0.75418559, -1.74485749],
       [-0.40775172, -0.38615505]])

In [20]:
print(np.add(arr3, arr4))  # 사칙연산
print(np.subtract(arr3, arr4))
print(np.multiply(arr3, arr4))
print(np.divide(arr3, arr4))

[[ 1.70946388 -1.24632166]
 [ 0.39273754 -2.18577423]
 [-1.47613687  0.0283971 ]]
[[ 0.60763156  1.21489945]
 [-1.11563363  1.30394075]
 [-0.66063344  0.8007072 ]]
[[ 0.63826267  0.01933426]
 [-0.27259891  0.76933688]
 [ 0.43563588 -0.16008141]]
[[ 2.10294742  0.01276692]
 [-0.4792561   0.25269499]
 [ 2.62018556 -1.07353807]]


In [30]:
print(np.maximum(arr3, arr4)) # 최대 최소
print(np.minimum(arr3, arr4)) 

[[-0.58166118  2.65719931]
 [ 2.10092546  0.43052403]
 [ 0.15194372  1.64200056]]
[[-1.50337954 -1.89469335]
 [ 0.7250137   0.08488157]
 [ 0.04388013 -0.18926315]]


In [33]:
print(arr3)
print(np.sum(arr3)) # 전체 성분
print(np.sum(arr3, axis = 0)) # 첫 번째 괄호가 사라졌을 때 덧셈

[[ 1.15854772 -0.01571111]
 [-0.36144805 -0.44091674]
 [-1.06838515  0.41455215]]
-0.3133611791983493
[-0.27128548 -0.0420757 ]


In [25]:
print(np.mean(arr3)) # 전체 평균
print(np.mean(arr3, axis = 0)) # 첫 번째 괄호가 사라졌을 때 평균

-0.05222686319972489
[-0.09042849 -0.01402523]


In [26]:
print(np.std(arr3)) # 표준편차
print(np.var(arr3)) # 분산
print(np.max(arr3)) # 최대값
print(np.min(arr3)) # 최소값

0.7029066285349876
0.49407772843842307
1.15854772153805
-1.068385154282249


In [28]:
print(np.argmax(arr3)) # 전체 성분의 최대값이 위치한 인덱스
print(np.argmin(arr3)) # 전체 성분의 최소값이 위치한 인덱스

0
4


In [30]:
print(arr3)
print(np.cumsum(arr3)) # 처음부터 마지막 성분까지의 누적합
print(np.cumprod(arr3)) # 처음부터 마지막 성분까지의 누적곱

[[ 1.15854772 -0.01571111]
 [-0.36144805 -0.44091674]
 [-1.06838515  0.41455215]]
[ 1.15854772  1.14283661  0.78138857  0.34047183 -0.72791333 -0.31336118]
[ 1.15854772 -0.01820207  0.0065791  -0.00290084  0.00309921  0.00128478]


In [32]:
print(np.sort(arr3))
print(np.sort(arr3)[:: -1])

[[-0.01571111  1.15854772]
 [-0.44091674 -0.36144805]
 [-1.06838515  0.41455215]]
[[-1.06838515  0.41455215]
 [-0.44091674 -0.36144805]
 [-0.01571111  1.15854772]]
